## Motivation and Theory of Projection.
### Motivation.

Projections are an important class of linear transformation and play an important role in Machine Learning (ML). In ML, we often deal with data that are high-dimensional. High-dimensional data are hard to analyse or to visualize. However high-dimensional data quite often possesses the property that only few dimensions contain most information, and most other dimensions are not essential to describe key properties of the data. More precisely we can project a high-dimensional data onto a lower-dimensional feature space and work in this lower-dimensional to learn more about the data and extract relevant patterns.
			
We will focus on the Orthogonal Projection and as inner product, we will use the dot-product defined as : for $y = [y_1, y_2,..., y_n]^T$ and $z = [z_1, z_2,..., z_n]^T$ in $\mathbb{R}^n$,
			\begin{align*}
				\langle y,z \rangle = y^{T} z = \sum_{i=1}^{n} y_i z_i.
			\end{align*}
		
Let $V$ a vector space and $U \subseteq V$ a subspace of $V$. A projection from $V$ to $U$ is a linear mapping $\Phi_{U} : V \to U$ such that $\Phi_{U} \circ \Phi_{U} = \Phi_{U}^2 = \Phi_{U}$. The projection matrix associated to $\Phi_{U}$ is denoted by $P_{\Phi}$ and satisfies the same property as $\Phi$ which is : $P_{\Phi} \circ P_{\Phi} = P_{\Phi}^2 = P_{\Phi}$.
			
### Theory

Let $V$ a vector space with dimension $n$. In this work, we will assume that $V = \mathbb{R}^{n}$. Let $U$ a subspace of $V$ of dimension $m$ and $\{ b_1, b_2,..., b_m\}$ a basis of $U$, where for all $i=1,...,m$, $b_i \in V$. Let $x \in V$ a high-dimensional data and $P_{\Phi}(x)$ its projection onto $U$. The goal is to project $x$ from the high-dimensional $n$ to the lower-dimensional $m$, ($m < n$). We are looking for $\lambda_1, \lambda_2,..,\lambda_m \in \mathbb{R}$ such that :
			\begin{align*}
				\Phi_{U}(x) = \sum_{i=1}^{m} \lambda_i b_i.
			\end{align*}
		
When projecting $x$ onto $U$, we are looking for the vector $\Phi_{U}(x)$ that is closest to $x$. So the quantity $\|x - \Phi_{U}(x)\|$ should be minimal, which implies that the vector $x - \Phi_{U}(x)$ should be orthogonal to $U$, that is for all $i=1,...,m$ :
			\begin{align*}
				\langle b_i, x - \Phi_{U}(x) \rangle = 0.
			\end{align*}
		
Let $B = [b_1\,\, b_2\,\, ...\,\, b_m] \in \mathbb{R}^{n\times m}$ be the matrix whose columns are vectors of the basis $\{ b_1, b_2,..., b_m\}$, $ \lambda = [\lambda_1, \lambda_2,..,\lambda_m ]^T$. Using the dot-product as inner product, for all $i = 1,...,m$, we have:
			\begin{align*}
				\langle b_i, x - \Phi_{U}(x) \rangle &= b_{i}^{T}(x - \Phi_{U}(x)) = 0, \text{ then } B^T(x - \Phi_{U}(x)) = 0,
			\end{align*}
			we have
$$\Phi_{U}(x) = \sum_{i=1}^{m} \lambda_i b_i = [b_1\,\, b_2\,\, ...\,\, b_m] [\lambda_1\,\,  \lambda_2\,\, ...\,\, \lambda_m ]^T = B \lambda$$
			then
			\begin{align*}
				B^T(x - \Phi_{U}(x)) = B^T(x - B \lambda) = 0, \text{ which implies } B^T B \lambda = B^T x
			\end{align*}
			thus
			\begin{align*}
				\lambda = (B^T B)^{-1}B^T x,
			\end{align*}
			therefore
			\begin{align*}
				\Phi_{U}(x) = B \lambda = B (B^T B)^{-1}B^T x.
			\end{align*}
			The projection matrix is defined by :
			\begin{align*}
				P_{\Phi} =  B (B^T B)^{-1}B^T.
			\end{align*}
			We can also write $\Phi_{U}(x) = \Phi_{span\{ b_1, b_2,..., b_m\}}(x)$, where $\{ b_1, b_2,..., b_m\}$ is a basis of $U$.

### Application: Gram-Schmidt Orthogonalization

It transforms any basis $\{ b_1, b_2,..., b_n\}$ of $n$-dimensional vector space $V$ into an orthogonal/orthonormal basis $\{ u_1, u_2,..., u_m\}$ of $V$, where :
			\begin{align*}
				& u_1 = b_1
				\\& u_k = b_k - \Phi_{span\{ u_1, u_2,..., u_{k-1}\}}(b_k),\,\,\, k = 2,\,3,\,...,\, n.
			\end{align*}
			Next we are going to implement Gram-Schmidt Orthogonalization on python.

In [1]:
import numpy as np

In [2]:
def projectionMatrix(B):
    a, b = B.shape
    if a==1:
        B = np.transpose(B)
        return np.dot(B,np.dot(np.linalg.inv(np.dot(np.transpose(B), B)), np.transpose(B)))
    return np.dot(B,np.dot(np.linalg.inv(np.dot(np.transpose(B), B)), np.transpose(B)))

#### Example of application for the projection matrix

In [3]:
B = np.array([[1,2,2]])
projectionMatrix(B)

array([[0.11111111, 0.22222222, 0.22222222],
       [0.22222222, 0.44444444, 0.44444444],
       [0.22222222, 0.44444444, 0.44444444]])

#### Projection of a vector x = [1,1,1] onto a line spanned by B

In [4]:
Y = np.dot(projectionMatrix(B), np.transpose(np.array([[1,1,1]])))
Y

array([[0.55555556],
       [1.11111111],
       [1.11111111]])

#### Projection matrix : Case of a plan spanned by b1 = [1,1,1] and b2 = [0,1,2]. We stacked those two vector in a matrix as columns.

In [5]:
projectionMatrix(np.array([[1,0],[1,1],[1,2]]))

array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

#### We will use the projection function defined above to code the Gram-Schmidt orthogonalization function

In [6]:
def GramSchmidthOrthogonalisation(B):
    U = np.zeros(B.shape)
    n, m = B.shape
    U[:,0] = B[:,0]
    V = np.transpose(np.array([B[:,0]]))
    
    for i in range(1,m):
        U[:,i] = (np.transpose(np.array([B[:,i]])) - np.dot(projectionMatrix(V), np.transpose(np.array([B[:,i]]))))[:,0]
        V = np.hstack((V,np.transpose(np.array([U[:,i]]))))
    return U

In [7]:
C = np.array([[1,0,1],[1,1,3],[1,2,-1]])
U = GramSchmidthOrthogonalisation(C)
print(U)

[[ 1. -1. -1.]
 [ 1.  0.  2.]
 [ 1.  1. -1.]]
